import React from 'react'
import ReactDOM from 'react-dom'
import './Aindex.less'

ReactDOM.render(
  <>
    {/* <T_SlideTitle /> */}
    {/* <T_Timer /> */}
    {/* <T_NormalTitle /> */}
    {/* <T_NumberFlop /> */}
    {/* <T_DropDownBox /> */}
    {/* <T_LczDatePicker /> */}
    {/* <T_Radio /> */}
    {/* <T_LczTabBar /> */}
    {/* <T_LczImage /> */}
    {/* <T_LczBorder /> */}
    {/* <T_LczCarouselTable /> */}
    {/* <T_LczIndicatorsTrends /> */}
    {/* <T_ProgressBar /> */}
    {/* <T_LczCustomGraphics /> */}
    {/* <T_MultilineText /> */}
    {/* <T_LczIconFont /> */}
    {/* <T_LczIframe /> */}
    {/* <T_LczButton /> */}
    {/* <T_LczFilterPanel /> */}
    {/* <T_LczOpeningVideo /> */}
    {/* <T_QrCode /> */}
    {/* <T_LczVideo /> */}
    {/* <T_LczStateBackground /> */}
    {/* <T_LczCarouselIframe /> */}
    {/* <T_LczDropdown /> */}
    {/* <T_LczCascader /> */}
    {/* <T_fullScreen /> */}
    {/* <T_LczVideoStream /> */}
    {/* <T_NewsList /> */}
    {/* <T_LczVoice /> */}
    {/* <T_LczStateCard /> */}
    {/* <T_LczSearch /> */}
    {/* <T_LczTextSearch /> */}
    {/* <T_circularTarget /> */}
    {/* <T_lczCanvas /> */}
    {/* <T_scrollPage /> */}
    {/* <T_lczbadge /> */}
    {/* <T_lczArrowPlotting /> */}
    {/* <T_weather /> */}
    {/* <T_LczSubwayLine /> */}
    {/* <T_weather /> */}
    {/* <T_LczSubwayLine /> */}
    {/* <T_LczCarouselImage /> */}
    {/* <T_LczCalendar /> */}
    {/* <T_carouselVideoSteam /> */}
    {/* <T_LczDateInterval /> */}
    {/* <T_Menu /> */}
    {/* <T_directoryTree /> */}
    {/* <LczCheckbox /> */}
    {/* <T_LczChina2dmap /> */}
    {/* <T_Lcz3dTorus /> */}
    {/* <T_LczBasicBar /> */}
    {/* <T_LczBasicStrip /> */}
    {/* <T_LczBasicLine /> */}
    {/* <T_LczBasicArea /> */}
    {/* <T_LczBasicPie /> */}
    {/* <T_LczBasicDoughnut /> */}
    {/* <T_LczNightingale /> */}
    {/* <T_LczBasicStereohistogram /> */}
    {/* <T_LczStackBar /> */}
    {/* <T_LczStackStrip /> */}
    {/* <T_LczStackArea /> */}
    {/* <T_LczScatter /> */}
    {/* <T_LczBasicBubble /> */}
    {/* <T_LczBasicFunnel /> */}
    {/* <T_LczBasicLineBar /> */}
    {/* <T_LczTangentialBar /> */}
    {/* <T_LczRadialPole /> */}
    {/* <T_LczTestTube /> */}
    {/* <T_LczBasicRadar /> */}
    {/* <T_LczWordCloud /> */}
    {/* <T_LczPercentageRing /> */}
    {/* <T_lczBasicAreaBar /> */}
    {/* <T_LczBasicGauge /> */}
    {/* <T_LczLeetBar /> */}
    {/* <T_LczWaterPolo /> */}
    {/* <T_lczAmap /> */}
    {/* <T_LczSingleSeriesStrip /> */}
    {/* <T_LczPercentageTrough /> */}
    {/* <T_LczMultilayerCircle /> */}
    {/* <T_LczStackAreaBar /> */}
    {/* <T_Lcz3dAreaMap /> */}
    {/* <T_LczFixedBubble /> */}
    {/* <T_LczSortBar /> */}
    {/* <T_LczDynamicLine /> */}
    {/* <T_RotateCard /> */}
    {/* <T_LczStackStereohistogram /> */}
    {/* <T_CardList /> */}
    {/* <T_LczHorizontalMenu /> */}
    {/* <T_LczColumnTable /> */}
    {/* <T_LczMechanicalBubble /> */}
    {/* <T_LczPagination /> */}
    {/* <T_LczScrollImage /> */}
    {/* <T_LczBarrage /> */}
    {/* <T_LczLightFlowPath /> */}
    {/* <T_LczTimeShaft /> */}
    {/* <T_LczPointTimeline /> */}
    {/* <T_LczCustomPath /> */}
    {/* <T_LczEarth /> */}
  </>,
  document.getElementById('root')
)
